doctrine:
    dbal:
        dbname: joopdt
        host: localhost
        port: 3306
        user: joopdt
        password: '%env(DATABASE_PASSWORD)%'
        driver: pdo_mysql
        server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.default
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
